# Generated by Django 6.0.2 on 2026-05-26 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_student_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="temp_password",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
